# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DrivingExperience(str, Enum):
    """
    DrivingExperience
    """

    """
    allowed enum values
    """
    LESS_MINUS_THAN_MINUS_THREE_MINUS_YEARS = 'less-than-three-years'
    MORE_MINUS_THAN_MINUS_THREE_MINUS_YEARS = 'more-than-three-years'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DrivingExperience from a JSON string"""
        return cls(json.loads(json_str))


