# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EnrichedPropertyMatchingStatus(str, Enum):
    """
    Статус проверки ответа кандидата по критериям вакансии.Возможные значения:<br/>  - `\"no_criteria\"` - к ответу не выставлены критерии<br/>  - `\"matched\"` - подошел под критерии<br/>  - `\"mismatched\"` - не подошел под критерии
    """

    """
    allowed enum values
    """
    NO_CRITERIA = 'no_criteria'
    MATCHED = 'matched'
    MISMATCHED = 'mismatched'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EnrichedPropertyMatchingStatus from a JSON string"""
        return cls(json.loads(json_str))


