# coding: utf-8

# flake8: noqa

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "ItemApi",
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AnalyticsRequest",
    "AnalyticsRequestFilter",
    "AnalyticsRequestSort",
    "AnalyticsResponse",
    "AnalyticsResponseResult",
    "AnalyticsResponseResultGroupingsInner",
    "AnalyticsResponseResultGroupingsInnerMetricsInner",
    "ApplyVas500Response",
    "ApplyVasRequest",
    "ApplyVasResp",
    "AuthError",
    "AuthErrorError",
    "BadRequestError",
    "BadRequestErrorError",
    "CallsStatsDay",
    "CallsStatsItem",
    "CallsStatsRequest",
    "CallsStatsResponse",
    "CallsStatsResponseResult",
    "ErrorResponse",
    "ErrorResponseError",
    "FieldError",
    "Groupings",
    "InfoVas",
    "ItemIdsRequestBody",
    "ItemInfoAvito",
    "ItemVasPricesResp",
    "ItemsInfoWithCategoryAvito",
    "ItemsInfoWithCategoryAvitoMeta",
    "ItemsInfoWithCategoryAvitoResourcesInner",
    "ItemsInfoWithCategoryAvitoResourcesInnerCategory",
    "NotFoundError",
    "NotFoundErrorError",
    "PackageIdRequestBodyV2",
    "PricesItemIdsRequestBody",
    "ServiceError",
    "ServiceErrorError",
    "ServiceUnavailableError",
    "ServiceUnavailableErrorError",
    "StatisticsCountersInner",
    "StatisticsCountersInnerStatsInner",
    "StatisticsPeriodGrouping",
    "StatisticsResponse",
    "StatisticsResponseResult",
    "StatisticsShallowRequestBody",
    "StickerResp",
    "UpdatePriceRequest",
    "UpdatePriceResponse",
    "UpdatePriceResponseResult",
    "ValidatingError",
    "ValidatingErrorError",
    "VasAmountAvito",
    "VasApplyAvito",
    "VasIdRequestBody",
    "VasPrices200Response",
    "VasResp",
]

# import apis into sdk package
from avito_ads.api.item_api import ItemApi as ItemApi
from avito_ads.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from avito_ads.api_response import ApiResponse as ApiResponse
from avito_ads.api_client import ApiClient as ApiClient
from avito_ads.configuration import Configuration as Configuration
from avito_ads.exceptions import OpenApiException as OpenApiException
from avito_ads.exceptions import ApiTypeError as ApiTypeError
from avito_ads.exceptions import ApiValueError as ApiValueError
from avito_ads.exceptions import ApiKeyError as ApiKeyError
from avito_ads.exceptions import ApiAttributeError as ApiAttributeError
from avito_ads.exceptions import ApiException as ApiException

# import models into sdk package
from avito_ads.models.analytics_request import AnalyticsRequest as AnalyticsRequest
from avito_ads.models.analytics_request_filter import AnalyticsRequestFilter as AnalyticsRequestFilter
from avito_ads.models.analytics_request_sort import AnalyticsRequestSort as AnalyticsRequestSort
from avito_ads.models.analytics_response import AnalyticsResponse as AnalyticsResponse
from avito_ads.models.analytics_response_result import AnalyticsResponseResult as AnalyticsResponseResult
from avito_ads.models.analytics_response_result_groupings_inner import AnalyticsResponseResultGroupingsInner as AnalyticsResponseResultGroupingsInner
from avito_ads.models.analytics_response_result_groupings_inner_metrics_inner import AnalyticsResponseResultGroupingsInnerMetricsInner as AnalyticsResponseResultGroupingsInnerMetricsInner
from avito_ads.models.apply_vas500_response import ApplyVas500Response as ApplyVas500Response
from avito_ads.models.apply_vas_request import ApplyVasRequest as ApplyVasRequest
from avito_ads.models.apply_vas_resp import ApplyVasResp as ApplyVasResp
from avito_ads.models.auth_error import AuthError as AuthError
from avito_ads.models.auth_error_error import AuthErrorError as AuthErrorError
from avito_ads.models.bad_request_error import BadRequestError as BadRequestError
from avito_ads.models.bad_request_error_error import BadRequestErrorError as BadRequestErrorError
from avito_ads.models.calls_stats_day import CallsStatsDay as CallsStatsDay
from avito_ads.models.calls_stats_item import CallsStatsItem as CallsStatsItem
from avito_ads.models.calls_stats_request import CallsStatsRequest as CallsStatsRequest
from avito_ads.models.calls_stats_response import CallsStatsResponse as CallsStatsResponse
from avito_ads.models.calls_stats_response_result import CallsStatsResponseResult as CallsStatsResponseResult
from avito_ads.models.error_response import ErrorResponse as ErrorResponse
from avito_ads.models.error_response_error import ErrorResponseError as ErrorResponseError
from avito_ads.models.field_error import FieldError as FieldError
from avito_ads.models.groupings import Groupings as Groupings
from avito_ads.models.info_vas import InfoVas as InfoVas
from avito_ads.models.item_ids_request_body import ItemIdsRequestBody as ItemIdsRequestBody
from avito_ads.models.item_info_avito import ItemInfoAvito as ItemInfoAvito
from avito_ads.models.item_vas_prices_resp import ItemVasPricesResp as ItemVasPricesResp
from avito_ads.models.items_info_with_category_avito import ItemsInfoWithCategoryAvito as ItemsInfoWithCategoryAvito
from avito_ads.models.items_info_with_category_avito_meta import ItemsInfoWithCategoryAvitoMeta as ItemsInfoWithCategoryAvitoMeta
from avito_ads.models.items_info_with_category_avito_resources_inner import ItemsInfoWithCategoryAvitoResourcesInner as ItemsInfoWithCategoryAvitoResourcesInner
from avito_ads.models.items_info_with_category_avito_resources_inner_category import ItemsInfoWithCategoryAvitoResourcesInnerCategory as ItemsInfoWithCategoryAvitoResourcesInnerCategory
from avito_ads.models.not_found_error import NotFoundError as NotFoundError
from avito_ads.models.not_found_error_error import NotFoundErrorError as NotFoundErrorError
from avito_ads.models.package_id_request_body_v2 import PackageIdRequestBodyV2 as PackageIdRequestBodyV2
from avito_ads.models.prices_item_ids_request_body import PricesItemIdsRequestBody as PricesItemIdsRequestBody
from avito_ads.models.service_error import ServiceError as ServiceError
from avito_ads.models.service_error_error import ServiceErrorError as ServiceErrorError
from avito_ads.models.service_unavailable_error import ServiceUnavailableError as ServiceUnavailableError
from avito_ads.models.service_unavailable_error_error import ServiceUnavailableErrorError as ServiceUnavailableErrorError
from avito_ads.models.statistics_counters_inner import StatisticsCountersInner as StatisticsCountersInner
from avito_ads.models.statistics_counters_inner_stats_inner import StatisticsCountersInnerStatsInner as StatisticsCountersInnerStatsInner
from avito_ads.models.statistics_period_grouping import StatisticsPeriodGrouping as StatisticsPeriodGrouping
from avito_ads.models.statistics_response import StatisticsResponse as StatisticsResponse
from avito_ads.models.statistics_response_result import StatisticsResponseResult as StatisticsResponseResult
from avito_ads.models.statistics_shallow_request_body import StatisticsShallowRequestBody as StatisticsShallowRequestBody
from avito_ads.models.sticker_resp import StickerResp as StickerResp
from avito_ads.models.update_price_request import UpdatePriceRequest as UpdatePriceRequest
from avito_ads.models.update_price_response import UpdatePriceResponse as UpdatePriceResponse
from avito_ads.models.update_price_response_result import UpdatePriceResponseResult as UpdatePriceResponseResult
from avito_ads.models.validating_error import ValidatingError as ValidatingError
from avito_ads.models.validating_error_error import ValidatingErrorError as ValidatingErrorError
from avito_ads.models.vas_amount_avito import VasAmountAvito as VasAmountAvito
from avito_ads.models.vas_apply_avito import VasApplyAvito as VasApplyAvito
from avito_ads.models.vas_id_request_body import VasIdRequestBody as VasIdRequestBody
from avito_ads.models.vas_prices200_response import VasPrices200Response as VasPrices200Response
from avito_ads.models.vas_resp import VasResp as VasResp

