# coding: utf-8

"""
    Авторизация

    Получение и обновление авторизационных токенов для персональной авторизации и авторизации приложений **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).**     

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_autorization.api.access_api import AccessApi


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccessApi()

    def tearDown(self) -> None:
        pass

    def test_get_access_token(self) -> None:
        """Test case for get_access_token

        Получение access token
        """
        pass


if __name__ == '__main__':
    unittest.main()
