# coding: utf-8

"""
    Авторизация

    Получение и обновление авторизационных токенов для персональной авторизации и авторизации приложений **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).**     

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_autorization.api.application_access_api import ApplicationAccessApi


class TestApplicationAccessApi(unittest.TestCase):
    """ApplicationAccessApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ApplicationAccessApi()

    def tearDown(self) -> None:
        pass

    def test_get_access_token_authorization_code(self) -> None:
        """Test case for get_access_token_authorization_code

        Получение access token
        """
        pass

    def test_refresh_access_token_authorization_code(self) -> None:
        """Test case for refresh_access_token_authorization_code

        Обновление access token
        """
        pass


if __name__ == '__main__':
    unittest.main()
