# coding: utf-8

"""
    Авторизация

    Получение и обновление авторизационных токенов для персональной авторизации и авторизации приложений **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).**     

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_autorization.models.refresh_access_token_authorization_code200_response import RefreshAccessTokenAuthorizationCode200Response

class TestRefreshAccessTokenAuthorizationCode200Response(unittest.TestCase):
    """RefreshAccessTokenAuthorizationCode200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RefreshAccessTokenAuthorizationCode200Response:
        """Test RefreshAccessTokenAuthorizationCode200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RefreshAccessTokenAuthorizationCode200Response`
        """
        model = RefreshAccessTokenAuthorizationCode200Response()
        if include_optional:
            return RefreshAccessTokenAuthorizationCode200Response(
                access_token = '',
                expires_in = 1.337,
                refresh_token = '',
                scope = '',
                token_type = ''
            )
        else:
            return RefreshAccessTokenAuthorizationCode200Response(
        )
        """

    def testRefreshAccessTokenAuthorizationCode200Response(self):
        """Test RefreshAccessTokenAuthorizationCode200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
