# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.get_dict_by_id200_response_inner import GetDictByID200ResponseInner

class TestGetDictByID200ResponseInner(unittest.TestCase):
    """GetDictByID200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetDictByID200ResponseInner:
        """Test GetDictByID200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetDictByID200ResponseInner`
        """
        model = GetDictByID200ResponseInner()
        if include_optional:
            return GetDictByID200ResponseInner(
                deprecated = True,
                id = 56,
                name = ''
            )
        else:
            return GetDictByID200ResponseInner(
        )
        """

    def testGetDictByID200ResponseInner(self):
        """Test GetDictByID200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
