# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy_create import VacancyCreate

class TestVacancyCreate(unittest.TestCase):
    """VacancyCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VacancyCreate:
        """Test VacancyCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VacancyCreate`
        """
        model = VacancyCreate()
        if include_optional:
            return VacancyCreate(
                address = '',
                administrator_organization_type = 56,
                age = avito_job.models.age_criteria.AgeCriteria(
                    from = 18, 
                    to = 65, ),
                age_preferences = olderThan45,
                allow_calls = True,
                allow_messages = True,
                apply_processing = avito_job.models.apply_processing.ApplyProcessing(
                    additional_questions = [
                        'experience'
                        ], 
                    apply_type = 'only_with_resume', ),
                billing_type = 'package',
                bonuses = ["pitanie","prozivanie"],
                business_area = 56,
                citizenship = ["rus"],
                construction_work_type = ["paintingWorks"],
                contacts = avito_job.models.contacts.Contacts(
                    email = '', 
                    name = '', 
                    phone = avito_job.models.phone.Phone(
                        city = '', 
                        country = '', 
                        number = '', ), ),
                coordinates = avito_job.models.coordinates.Coordinates(
                    latitude = 1.337, 
                    longitude = 1.337, ),
                cuisine = ["russian"],
                custom_employer_name = '',
                delivery_method = [
                    'car'
                    ],
                description = '',
                driving_experience = avito_job.models.vacancy_create_driving_experience.VacancyCreate_driving_experience(
                    id = 'noExperience', ),
                driving_license_category = [
                    'A'
                    ],
                eatery_type = ["cafe"],
                education_level = '["higher"]',
                employee_id = 56,
                employment = '',
                experience = avito_job.models.vacancy_create_experience.VacancyCreate_experience(
                    id = 'noMatter', ),
                facility_type = ["production"],
                food_production_shop_type = ["cold"],
                grade = '["lead"]',
                html_tags = True,
                image_url = '',
                is_company_car = True,
                is_side_job = True,
                medical_book = '["registerByCandidate"]',
                medical_specialization = ["Вирусолок","Терапевт"],
                medical_specialization_ids = [3265936,3265937],
                name = '',
                payout_frequency = avito_job.models.vacancy_create_payout_frequency.VacancyCreate_payout_frequency(
                    id = 'dailyPay', ),
                profession = 56,
                registration_method = ["contract","gph_individual"],
                retail_equipment_type = ["cashRegisterAndPosTerminals"],
                retail_shop_type = ["hypermarketOrSupermarket"],
                salary = 56,
                salary_detail = avito_job.models.salary_detail.SalaryDetail(
                    base = avito_job.models.salary_detail_base.SalaryDetail_base(
                        bonus = '5% от продаж в месяц', 
                        range = avito_job.models.salary_base_range.SalaryBaseRange(
                            from = 30000, 
                            to = 60000, ), ), 
                    paid_period = '["month"]', 
                    taxes = '["gross"]', ),
                salary_range = avito_job.models.vacancy_create_salary_range.VacancyCreate_salary_range(
                    from = 30000, 
                    to = 60000, ),
                schedule = avito_job.models.vacancy_create_schedule.VacancyCreate_schedule(
                    id = 'flyInFlyOut', ),
                shifts = [
                    56
                    ],
                tools_availability = '["needYourOwn"]',
                vacancy_code = '',
                vehicle_type = 56,
                work_days_per_week = [
                    56
                    ],
                work_format = [
                    'office'
                    ],
                work_hours_per_day = [
                    56
                    ],
                worker_class = ["1"]
            )
        else:
            return VacancyCreate(
                billing_type = 'package',
                business_area = 56,
                description = '',
                employment = '',
                experience = avito_job.models.vacancy_create_experience.VacancyCreate_experience(
                    id = 'noMatter', ),
                name = '',
                schedule = avito_job.models.vacancy_create_schedule.VacancyCreate_schedule(
                    id = 'flyInFlyOut', ),
        )
        """

    def testVacancyCreate(self):
        """Test VacancyCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
