# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.search_vacancy403_response import SearchVacancy403Response

class TestSearchVacancy403Response(unittest.TestCase):
    """SearchVacancy403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SearchVacancy403Response:
        """Test SearchVacancy403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SearchVacancy403Response`
        """
        model = SearchVacancy403Response()
        if include_optional:
            return SearchVacancy403Response(
                error = avito_job.models.search_vacancy_403_response_error.searchVacancy_403_response_error(
                    code = 403, 
                    message = 'Forbidden', )
            )
        else:
            return SearchVacancy403Response(
        )
        """

    def testSearchVacancy403Response(self):
        """Test SearchVacancy403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
