# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy_v2_create_location import VacancyV2CreateLocation

class TestVacancyV2CreateLocation(unittest.TestCase):
    """VacancyV2CreateLocation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VacancyV2CreateLocation:
        """Test VacancyV2CreateLocation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VacancyV2CreateLocation`
        """
        model = VacancyV2CreateLocation()
        if include_optional:
            return VacancyV2CreateLocation(
                address = avito_job.models.location_address.LocationAddress(
                    area = 'городской округ Новосибирск', 
                    house = '117', 
                    locality = 'Новосибирск', 
                    province = 'Новосибирская область', 
                    region = 'Сибирский федеральный округ', 
                    street = 'Вертковская улица', ),
                coordinates = avito_job.models.coordinates.Coordinates(
                    latitude = 1.337, 
                    longitude = 1.337, )
            )
        else:
            return VacancyV2CreateLocation(
        )
        """

    def testVacancyV2CreateLocation(self):
        """Test VacancyV2CreateLocation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
