# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.resume_contacts import ResumeContacts

class TestResumeContacts(unittest.TestCase):
    """ResumeContacts unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResumeContacts:
        """Test ResumeContacts
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResumeContacts`
        """
        model = ResumeContacts()
        if include_optional:
            return ResumeContacts(
                already_bought = False,
                contacts = [{"type":"e-mail","value":"candidate@example.com"},{"type":"phone","value":79211234455},{"type":"chat_id","value":"u2i-voDBaJ_nyscu9ztBC3TTaW"}],
                full_name = avito_job.models.get_applications_by_ids_result_applies_inner_applicant_data_full_name.GetApplicationsByIdsResult_applies_inner_applicant_data_full_name(
                    first_name = 'Иван', 
                    last_name = 'Иванов', 
                    patronymic = 'Иванович', ),
                name = 'Иванов Иван'
            )
        else:
            return ResumeContacts(
        )
        """

    def testResumeContacts(self):
        """Test ResumeContacts"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
