# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.bad_request import BadRequest

class TestBadRequest(unittest.TestCase):
    """BadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BadRequest:
        """Test BadRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BadRequest`
        """
        model = BadRequest()
        if include_optional:
            return BadRequest(
                error = avito_job.models.bad_request_error.BadRequest_error(
                    reason = 'is_empty', 
                    type = 'bad_json_data', 
                    value = 'billing_type', )
            )
        else:
            return BadRequest(
        )
        """

    def testBadRequest(self):
        """Test BadRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
