# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.enriched_properties_age import EnrichedPropertiesAge

class TestEnrichedPropertiesAge(unittest.TestCase):
    """EnrichedPropertiesAge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnrichedPropertiesAge:
        """Test EnrichedPropertiesAge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrichedPropertiesAge`
        """
        model = EnrichedPropertiesAge()
        if include_optional:
            return EnrichedPropertiesAge(
                matching_status = 'no_criteria',
                value = 56
            )
        else:
            return EnrichedPropertiesAge(
        )
        """

    def testEnrichedPropertiesAge(self):
        """Test EnrichedPropertiesAge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
