# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy20_params_salary import Vacancy20ParamsSalary

class TestVacancy20ParamsSalary(unittest.TestCase):
    """Vacancy20ParamsSalary unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vacancy20ParamsSalary:
        """Test Vacancy20ParamsSalary
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vacancy20ParamsSalary`
        """
        model = Vacancy20ParamsSalary()
        if include_optional:
            return Vacancy20ParamsSalary(
                var_from = 30000,
                to = 60000
            )
        else:
            return Vacancy20ParamsSalary(
        )
        """

    def testVacancy20ParamsSalary(self):
        """Test Vacancy20ParamsSalary"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
