# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.resume20_params import Resume20Params

class TestResume20Params(unittest.TestCase):
    """Resume20Params unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resume20Params:
        """Test Resume20Params
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resume20Params`
        """
        model = Resume20Params()
        if include_optional:
            return Resume20Params(
                ability_to_business_trip = 'Не готов',
                address = 'Москва, Лесная улица 7',
                age = 32,
                business_area = 'IT, интернет, телеком',
                driver_licence = 'true',
                driver_licence_category = [
                    'a'
                    ],
                education = 'Высшее',
                education_list = [
                    avito_job.models.resume2_0_params_education_list_inner.Resume2_0_params_education_list_inner(
                        education_stop = '1995', 
                        institution = 'МГИМО МИД РФ', 
                        specialty = 'Финансы и кредит, экономист-международник', )
                    ],
                experience_list = [
                    avito_job.models.resume2_0_params_experience_list_inner.Resume2_0_params_experience_list_inner(
                        company = 'МТС', 
                        position = 'Эксперт клиентского сервиса', 
                        responsibilities = 'Принятие входящих обращений от клиентов; помощь в решении возникающих вопросов; консультирование по продуктам компании; продажи', 
                        work_finish = 'Sat Sep 01 04:00:00 GMT+04:00 2018', 
                        work_start = 'Wed Jul 01 04:00:00 GMT+04:00 2015', )
                    ],
                language_list = [
                    avito_job.models.resume2_0_params_language_list_inner.Resume2_0_params_language_list_inner(
                        language = 'Коми', 
                        language_level = 'Начальный', )
                    ],
                moving = 'Невозможен',
                nationality = 'Филиппины',
                pol = 'Мужской',
                razreshenie_na_rabotu_v_rossii = 'Да',
                schedule = 'flyInFlyOut'
            )
        else:
            return Resume20Params(
        )
        """

    def testResume20Params(self):
        """Test Resume20Params"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
