# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.item_not_found_error_error import ItemNotFoundErrorError

class TestItemNotFoundErrorError(unittest.TestCase):
    """ItemNotFoundErrorError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemNotFoundErrorError:
        """Test ItemNotFoundErrorError
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemNotFoundErrorError`
        """
        model = ItemNotFoundErrorError()
        if include_optional:
            return ItemNotFoundErrorError(
                type = 'vacancies',
                value = 'chosen_vacancy_is_not_found'
            )
        else:
            return ItemNotFoundErrorError(
        )
        """

    def testItemNotFoundErrorError(self):
        """Test ItemNotFoundErrorError"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
