# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy_v2_create_hierarchy import VacancyV2CreateHierarchy

class TestVacancyV2CreateHierarchy(unittest.TestCase):
    """VacancyV2CreateHierarchy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VacancyV2CreateHierarchy:
        """Test VacancyV2CreateHierarchy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VacancyV2CreateHierarchy`
        """
        model = VacancyV2CreateHierarchy()
        if include_optional:
            return VacancyV2CreateHierarchy(
                employee_id = 56
            )
        else:
            return VacancyV2CreateHierarchy(
        )
        """

    def testVacancyV2CreateHierarchy(self):
        """Test VacancyV2CreateHierarchy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
