# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy_education_level import VacancyEducationLevel

class TestVacancyEducationLevel(unittest.TestCase):
    """VacancyEducationLevel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVacancyEducationLevel(self):
        """Test VacancyEducationLevel"""
        # inst = VacancyEducationLevel()

if __name__ == '__main__':
    unittest.main()
