# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy20_address_details_coordinates import Vacancy20AddressDetailsCoordinates

class TestVacancy20AddressDetailsCoordinates(unittest.TestCase):
    """Vacancy20AddressDetailsCoordinates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vacancy20AddressDetailsCoordinates:
        """Test Vacancy20AddressDetailsCoordinates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vacancy20AddressDetailsCoordinates`
        """
        model = Vacancy20AddressDetailsCoordinates()
        if include_optional:
            return Vacancy20AddressDetailsCoordinates(
                latitude = 55.778644,
                longitude = 37.587901
            )
        else:
            return Vacancy20AddressDetailsCoordinates(
        )
        """

    def testVacancy20AddressDetailsCoordinates(self):
        """Test Vacancy20AddressDetailsCoordinates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
