# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.vacancy20_address_details import Vacancy20AddressDetails

class TestVacancy20AddressDetails(unittest.TestCase):
    """Vacancy20AddressDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vacancy20AddressDetails:
        """Test Vacancy20AddressDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vacancy20AddressDetails`
        """
        model = Vacancy20AddressDetails()
        if include_optional:
            return Vacancy20AddressDetails(
                address = 'Санкт-Петербург, Пушкин, Малая улица, 12',
                city = 'Пушкин',
                coordinates = avito_job.models.vacancy2_0_address_details_coordinates.Vacancy2_0_addressDetails_coordinates(
                    latitude = 55.778644, 
                    longitude = 37.587901, ),
                province = 'Новосибирская область'
            )
        else:
            return Vacancy20AddressDetails(
        )
        """

    def testVacancy20AddressDetails(self):
        """Test Vacancy20AddressDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
