# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.resumes_get200_response import ResumesGet200Response

class TestResumesGet200Response(unittest.TestCase):
    """ResumesGet200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResumesGet200Response:
        """Test ResumesGet200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResumesGet200Response`
        """
        model = ResumesGet200Response()
        if include_optional:
            return ResumesGet200Response(
                meta = avito_job.models.мета_информация_ответа.Мета-информация ответа(
                    cursor = 1538480436, 
                    page = 1, 
                    pages = 6, 
                    per_page = 25, ),
                resumes = [
                    avito_job.models.общая_информация_резюме.Общая информация резюме(
                        age = 19, 
                        created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        driver_licence = 'true', 
                        driver_licence_category = [
                            'a'
                            ], 
                        driving_experience = 'less-than-three-years', 
                        education_level = 'unfinished-higher', 
                        gender = 'female', 
                        id = 2385934235, 
                        is_purchased = False, 
                        location = avito_job.models.регион.Регион(
                            id = 637640, 
                            title = 'Москва', ), 
                        medical_book = 'true', 
                        nationality = avito_job.models.гражданство.Гражданство(
                            id = 15973, 
                            title = 'Россия', ), 
                        own_transport = 'false', 
                        salary = 20000, 
                        specialization = avito_job.models.сфера_деятельности.Сфера деятельности(
                            id = 10186, 
                            title = 'Консультирование', ), 
                        title = 'Оператор Call-центра', 
                        total_experience = 0, 
                        updated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return ResumesGet200Response(
        )
        """

    def testResumesGet200Response(self):
        """Test ResumesGet200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
