# coding: utf-8

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_job.models.resume20_params_experience_list_inner import Resume20ParamsExperienceListInner

class TestResume20ParamsExperienceListInner(unittest.TestCase):
    """Resume20ParamsExperienceListInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Resume20ParamsExperienceListInner:
        """Test Resume20ParamsExperienceListInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Resume20ParamsExperienceListInner`
        """
        model = Resume20ParamsExperienceListInner()
        if include_optional:
            return Resume20ParamsExperienceListInner(
                company = 'МТС',
                position = 'Эксперт клиентского сервиса',
                responsibilities = 'Принятие входящих обращений от клиентов; помощь в решении возникающих вопросов; консультирование по продуктам компании; продажи',
                work_finish = 'Sat Sep 01 04:00:00 GMT+04:00 2018',
                work_start = 'Wed Jul 01 04:00:00 GMT+04:00 2015'
            )
        else:
            return Resume20ParamsExperienceListInner(
        )
        """

    def testResume20ParamsExperienceListInner(self):
        """Test Resume20ParamsExperienceListInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
