# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.post_send_message200_response_content import PostSendMessage200ResponseContent

class TestPostSendMessage200ResponseContent(unittest.TestCase):
    """PostSendMessage200ResponseContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSendMessage200ResponseContent:
        """Test PostSendMessage200ResponseContent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSendMessage200ResponseContent`
        """
        model = PostSendMessage200ResponseContent()
        if include_optional:
            return PostSendMessage200ResponseContent(
                text = 'привет'
            )
        else:
            return PostSendMessage200ResponseContent(
        )
        """

    def testPostSendMessage200ResponseContent(self):
        """Test PostSendMessage200ResponseContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
