# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.post_send_image_message200_response_content_image import PostSendImageMessage200ResponseContentImage

class TestPostSendImageMessage200ResponseContentImage(unittest.TestCase):
    """PostSendImageMessage200ResponseContentImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostSendImageMessage200ResponseContentImage:
        """Test PostSendImageMessage200ResponseContentImage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostSendImageMessage200ResponseContentImage`
        """
        model = PostSendImageMessage200ResponseContentImage()
        if include_optional:
            return PostSendImageMessage200ResponseContentImage(
                sizes = {"1280x960":"https://example.hosts.ru/image_1280_960.png","140x105":"https://example.hosts.ru/image_140_105.png","32x32":"https://example.hosts.ru/image_32_32.png"}
            )
        else:
            return PostSendImageMessage200ResponseContentImage(
        )
        """

    def testPostSendImageMessage200ResponseContentImage(self):
        """Test PostSendImageMessage200ResponseContentImage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
