# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.chat_users_inner_public_user_profile_avatar_images import ChatUsersInnerPublicUserProfileAvatarImages

class TestChatUsersInnerPublicUserProfileAvatarImages(unittest.TestCase):
    """ChatUsersInnerPublicUserProfileAvatarImages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatUsersInnerPublicUserProfileAvatarImages:
        """Test ChatUsersInnerPublicUserProfileAvatarImages
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatUsersInnerPublicUserProfileAvatarImages`
        """
        model = ChatUsersInnerPublicUserProfileAvatarImages()
        if include_optional:
            return ChatUsersInnerPublicUserProfileAvatarImages(
                var_128x128 = 'https://www.avito.st/stub_avatars/_/14_128x128.png',
                var_192x192 = 'https://www.avito.st/stub_avatars/_/14_192x192.png',
                var_24x24 = 'https://www.avito.st/stub_avatars/_/14_24x24.png',
                var_256x256 = 'https://www.avito.st/stub_avatars/_/14_256x256.png',
                var_36x36 = 'https://www.avito.st/stub_avatars/_/14_36x36.png',
                var_48x48 = 'https://www.avito.st/stub_avatars/_/14_48x48.png',
                var_64x64 = 'https://www.avito.st/stub_avatars/_/14_64x64.png',
                var_72x72 = 'https://www.avito.st/stub_avatars/_/14_72x72.png',
                var_96x96 = 'https://www.avito.st/stub_avatars/_/14_96x96.png'
            )
        else:
            return ChatUsersInnerPublicUserProfileAvatarImages(
        )
        """

    def testChatUsersInnerPublicUserProfileAvatarImages(self):
        """Test ChatUsersInnerPublicUserProfileAvatarImages"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
