# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.get_subscriptions200_response_subscriptions_inner import GetSubscriptions200ResponseSubscriptionsInner

class TestGetSubscriptions200ResponseSubscriptionsInner(unittest.TestCase):
    """GetSubscriptions200ResponseSubscriptionsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSubscriptions200ResponseSubscriptionsInner:
        """Test GetSubscriptions200ResponseSubscriptionsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSubscriptions200ResponseSubscriptionsInner`
        """
        model = GetSubscriptions200ResponseSubscriptionsInner()
        if include_optional:
            return GetSubscriptions200ResponseSubscriptionsInner(
                url = 'http://abc',
                version = '3'
            )
        else:
            return GetSubscriptions200ResponseSubscriptionsInner(
                url = 'http://abc',
                version = '3',
        )
        """

    def testGetSubscriptions200ResponseSubscriptionsInner(self):
        """Test GetSubscriptions200ResponseSubscriptionsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
