# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.chat_context_value_images_main import ChatContextValueImagesMain

class TestChatContextValueImagesMain(unittest.TestCase):
    """ChatContextValueImagesMain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatContextValueImagesMain:
        """Test ChatContextValueImagesMain
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatContextValueImagesMain`
        """
        model = ChatContextValueImagesMain()
        if include_optional:
            return ChatContextValueImagesMain(
                var_140x105 = 'https://01-img-staging-proxy.k.avito.ru/140x105/5815183159.jpg'
            )
        else:
            return ChatContextValueImagesMain(
        )
        """

    def testChatContextValueImagesMain(self):
        """Test ChatContextValueImagesMain"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
