# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.models.chats import Chats

class TestChats(unittest.TestCase):
    """Chats unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Chats:
        """Test Chats
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Chats`
        """
        model = Chats()
        if include_optional:
            return Chats(
                chats = [
                    avito_messenger.models.chat.Chat(
                        context = avito_messenger.models.chat_context.Chat_context(
                            type = 'item', 
                            value = avito_messenger.models.chat_context_value.Chat_context_value(
                                id = 1768287444, 
                                images = avito_messenger.models.chat_context_value_images.Chat_context_value_images(
                                    count = 4, 
                                    main = avito_messenger.models.chat_context_value_images_main.Chat_context_value_images_main(
                                        140x105 = 'https://01-img-staging-proxy.k.avito.ru/140x105/5815183159.jpg', ), ), 
                                price_string = '300 000 ₽', 
                                status_id = 10, 
                                title = 'Mazda 3 2008', 
                                url = 'https://avito.ru/moskva/avtomobili/mazda_3_2008_1768287444', 
                                user_id = 141906442, ), ), 
                        created = 1571412836, 
                        id = '', 
                        last_message = avito_messenger.models.chat_last_message.Chat_last_message(
                            author_id = 94235311, 
                            content = avito_messenger.models.message_content.MessageContent(
                                call = avito_messenger.models.message_content_call.MessageContent_call(
                                    status = 'missed', 
                                    target_user_id = 94235311, ), 
                                flow_id = 'seller_audience_discount', 
                                image = avito_messenger.models.message_content_image.MessageContent_image(
                                    sizes = {"1280x960":"https://img.k.avito.ru/chat/1280x960/5083651369.3e798a9bf88345ae8fe85ff891266b24.jpg","140x105":"https://img.k.avito.ru/chat/140x105/5083651369.3e798a9bf88345ae8fe85ff891266b24.jpg","32x32":"https://img.k.avito.ru/chat/32x32/5083651369.3e798a9bf88345ae8fe85ff891266b24.jpg","640x480":"https://img.k.avito.ru/chat/640x480/5083651369.3e798a9bf88345ae8fe85ff891266b24.jpg"}, ), 
                                item = avito_messenger.models.message_content_item.MessageContent_item(
                                    image_url = 'https://avito.ru/image_url.webp', 
                                    item_url = 'https://avito.ru/item_url', 
                                    price_string = '1 232 323 ₽', 
                                    title = 'Объявление', ), 
                                link = avito_messenger.models.message_content_link.MessageContent_link(
                                    preview = avito_messenger.models.message_content_link_preview.MessageContent_link_preview(
                                        description = 'Лучшие публикации за последние 24 часа', 
                                        domain = 'habr.com', 
                                        title = 'Лучшие публикации за сутки / Хабр', 
                                        url = 'https://habr.com/ru/', ), 
                                    text = 'habr.com', 
                                    url = 'habr.com', ), 
                                location = avito_messenger.models.message_content_location.MessageContent_location(
                                    kind = 'street', 
                                    lat = 55.599799, 
                                    lon = 37.603954, 
                                    text = 'Москва, Варшавское шоссе', 
                                    title = 'Москва, Варшавское шоссе', ), 
                                text = 'привет!', 
                                voice = avito_messenger.models.message_content_voice.MessageContent_voice(
                                    voice_id = '', ), ), 
                            created = 1571654040, 
                            direction = 'out', 
                            id = '', 
                            type = 'link', ), 
                        updated = 1571654040, 
                        users = [
                            avito_messenger.models.chat_users_inner.Chat_users_inner(
                                id = 94235311, 
                                name = 'Guldan', 
                                public_user_profile = avito_messenger.models.chat_users_inner_public_user_profile.Chat_users_inner_public_user_profile(
                                    avatar = avito_messenger.models.chat_users_inner_public_user_profile_avatar.Chat_users_inner_public_user_profile_avatar(
                                        default = 'https://www.avito.st/stub_avatars/_/14_256x256.png', ), 
                                    item_id = 1768287444, 
                                    url = 'https://avito.ru/user/db65c00c946dc404e11f14755465453b/profile', 
                                    user_id = 94235311, ), )
                            ], )
                    ]
            )
        else:
            return Chats(
        )
        """

    def testChats(self):
        """Test Chats"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
