# coding: utf-8

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_messenger.api.messenger_api import MessengerApi


class TestMessengerApi(unittest.TestCase):
    """MessengerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MessengerApi()

    def tearDown(self) -> None:
        pass

    def test_chat_read(self) -> None:
        """Test case for chat_read

        Прочитать чат
        """
        pass

    def test_delete_message(self) -> None:
        """Test case for delete_message

        Удаление сообщения
        """
        pass

    def test_get_chat_by_id_v2(self) -> None:
        """Test case for get_chat_by_id_v2

        Получение информации по чату
        """
        pass

    def test_get_chats_v2(self) -> None:
        """Test case for get_chats_v2

        Получение информации по чатам
        """
        pass

    def test_get_messages_v3(self) -> None:
        """Test case for get_messages_v3

        Получение списка сообщений V3
        """
        pass

    def test_get_subscriptions(self) -> None:
        """Test case for get_subscriptions

        Получение подписок (webhooks)
        """
        pass

    def test_get_voice_files(self) -> None:
        """Test case for get_voice_files

        Получение голосовых сообщений
        """
        pass

    def test_post_blacklist_v2(self) -> None:
        """Test case for post_blacklist_v2

        Добавление пользователя в blacklist
        """
        pass

    def test_post_send_image_message(self) -> None:
        """Test case for post_send_image_message

        Отправка сообщения с изображением
        """
        pass

    def test_post_send_message(self) -> None:
        """Test case for post_send_message

        Отправка сообщения
        """
        pass

    def test_post_webhook_unsubscribe(self) -> None:
        """Test case for post_webhook_unsubscribe

        Отключение уведомлений (webhooks)
        """
        pass

    def test_post_webhook_v3(self) -> None:
        """Test case for post_webhook_v3

        Включение уведомлений V3 (webhooks)
        """
        pass

    def test_upload_images(self) -> None:
        """Test case for upload_images

        Загрузка изображений
        """
        pass


if __name__ == '__main__':
    unittest.main()
