# coding: utf-8

# flake8: noqa

"""
    Авито.Работа

    API для размещения, редактирования и снятия с публикации вакансии Авито Работа **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "JobApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ActivationForbiddenError",
    "ActivationForbiddenErrorError",
    "AgeCriteria",
    "ApplicationsGetByIdsRequest",
    "ApplicationsSetIsViewedRequest",
    "ApplicationsSetIsViewedRequestAppliesInner",
    "ApplicationsWebhookDelete200Response",
    "ApplyProcessing",
    "AuthError",
    "AuthErrorError",
    "BadRequest",
    "BadRequestError",
    "BadRequestErrorError",
    "BadRequestOnVacancy",
    "BadRequestShort",
    "BadRequestShortError",
    "Citizenship",
    "Contacts",
    "Coordinates",
    "CreationForbiddenError",
    "CreationForbiddenErrorError",
    "DriverLicence",
    "DrivingExperience",
    "EditingForbiddenError",
    "EditingForbiddenErrorError",
    "EducationLevel",
    "EnrichedProperties",
    "EnrichedPropertiesAge",
    "EnrichedPropertiesCitizenship",
    "EnrichedPropertiesExperience",
    "EnrichedPropertiesFullName",
    "EnrichedPropertiesGender",
    "EnrichedPropertiesPhone",
    "EnrichedPropertyMatchingStatus",
    "ForbiddenError",
    "ForbiddenErrorError",
    "Gender",
    "GetApplicationsByIdsResult",
    "GetApplicationsByIdsResultAppliesInner",
    "GetApplicationsByIdsResultAppliesInnerApplicant",
    "GetApplicationsByIdsResultAppliesInnerApplicantData",
    "GetApplicationsByIdsResultAppliesInnerApplicantDataFullName",
    "GetApplicationsByIdsResultAppliesInnerContacts",
    "GetApplicationsByIdsResultAppliesInnerContactsChat",
    "GetApplicationsByIdsResultAppliesInnerContactsPhonesInner",
    "GetApplicationsByIdsResultAppliesInnerPrevalidation",
    "GetApplicationsByIdsResultAppliesInnerPrice",
    "GetApplicationsIdsResult",
    "GetApplicationsIdsResultAppliesInner",
    "GetDictByID200ResponseInner",
    "GetDicts200ResponseInner",
    "Grade",
    "ItemNotFoundError",
    "ItemNotFoundErrorError",
    "Location",
    "LocationAddress",
    "MedicalBook",
    "MedicalBookVacancy",
    "NotFoundError",
    "NotFoundErrorError",
    "OwnTransport",
    "PaidPeriod",
    "PaymentError",
    "PaymentErrorError",
    "Phone",
    "Photo",
    "PrevalidationAnswer",
    "PurchasingError",
    "PurchasingErrorError",
    "Resume20",
    "Resume20Params",
    "Resume20ParamsEducationListInner",
    "Resume20ParamsExperienceListInner",
    "Resume20ParamsLanguageListInner",
    "ResumeContact",
    "ResumeContacts",
    "ResumeSearchMeta",
    "ResumesGet200Response",
    "SalaryBaseRange",
    "SalaryDetail",
    "SalaryDetailBase",
    "SearchVacancy200Response",
    "SearchVacancy403Response",
    "SearchVacancy403ResponseError",
    "ServiceError",
    "ServiceErrorError",
    "ServiceUnavailableError",
    "ServiceUnavailableErrorError",
    "SetApplicationsisVewedResult",
    "SetApplicationsisVewedResultAppliesInner",
    "SimplifiedResume",
    "SimplifiedVacancy",
    "SimplifiedVacancyAddressDetails",
    "Specialization",
    "StoppingForbiddenError",
    "StoppingForbiddenErrorError",
    "Taxes",
    "TooManyRequestsError",
    "TooManyRequestsErrorError",
    "ToolsAvailability",
    "VacanciesGetByIdsBody",
    "Vacancy20",
    "Vacancy20AddressDetails",
    "Vacancy20AddressDetailsCoordinates",
    "Vacancy20Params",
    "Vacancy20ParamsCoordinates",
    "Vacancy20ParamsSalary",
    "Vacancy20ParamsSalaryBaseRange",
    "VacancyArchive",
    "VacancyAutoRenewal",
    "VacancyCreate",
    "VacancyCreateDrivingExperience",
    "VacancyCreateExperience",
    "VacancyCreatePayoutFrequency",
    "VacancyCreateResult",
    "VacancyCreateSalaryRange",
    "VacancyCreateSchedule",
    "VacancyEducationLevel",
    "VacancyProlongate",
    "VacancySearchMeta",
    "VacancyStatusesBody",
    "VacancyStatusesResultInner",
    "VacancyStatusesResultInnerLastAction",
    "VacancyStatusesResultInnerLastActionError",
    "VacancyStatusesResultInnerVacancy",
    "VacancyUpdate",
    "VacancyUpdatePayoutFrequency",
    "VacancyUpdateSalaryRange",
    "VacancyV2Create",
    "VacancyV2CreateContacts",
    "VacancyV2CreateHierarchy",
    "VacancyV2CreateLocation",
    "VacancyV2CreateResult",
    "VacancyV2CreateSalary",
    "ValidatingError",
    "ValidatingErrorError",
    "VerificationNeededError",
    "VerificationNeededErrorError",
    "WebhookSubscribeRequestBody",
    "WebhooksSubscriptionResultList",
]

# import apis into sdk package
from avito_job.api.job_api import JobApi as JobApi

# import ApiClient
from avito_job.api_response import ApiResponse as ApiResponse
from avito_job.api_client import ApiClient as ApiClient
from avito_job.configuration import Configuration as Configuration
from avito_job.exceptions import OpenApiException as OpenApiException
from avito_job.exceptions import ApiTypeError as ApiTypeError
from avito_job.exceptions import ApiValueError as ApiValueError
from avito_job.exceptions import ApiKeyError as ApiKeyError
from avito_job.exceptions import ApiAttributeError as ApiAttributeError
from avito_job.exceptions import ApiException as ApiException

# import models into sdk package
from avito_job.models.activation_forbidden_error import ActivationForbiddenError as ActivationForbiddenError
from avito_job.models.activation_forbidden_error_error import ActivationForbiddenErrorError as ActivationForbiddenErrorError
from avito_job.models.age_criteria import AgeCriteria as AgeCriteria
from avito_job.models.applications_get_by_ids_request import ApplicationsGetByIdsRequest as ApplicationsGetByIdsRequest
from avito_job.models.applications_set_is_viewed_request import ApplicationsSetIsViewedRequest as ApplicationsSetIsViewedRequest
from avito_job.models.applications_set_is_viewed_request_applies_inner import ApplicationsSetIsViewedRequestAppliesInner as ApplicationsSetIsViewedRequestAppliesInner
from avito_job.models.applications_webhook_delete200_response import ApplicationsWebhookDelete200Response as ApplicationsWebhookDelete200Response
from avito_job.models.apply_processing import ApplyProcessing as ApplyProcessing
from avito_job.models.auth_error import AuthError as AuthError
from avito_job.models.auth_error_error import AuthErrorError as AuthErrorError
from avito_job.models.bad_request import BadRequest as BadRequest
from avito_job.models.bad_request_error import BadRequestError as BadRequestError
from avito_job.models.bad_request_error_error import BadRequestErrorError as BadRequestErrorError
from avito_job.models.bad_request_on_vacancy import BadRequestOnVacancy as BadRequestOnVacancy
from avito_job.models.bad_request_short import BadRequestShort as BadRequestShort
from avito_job.models.bad_request_short_error import BadRequestShortError as BadRequestShortError
from avito_job.models.citizenship import Citizenship as Citizenship
from avito_job.models.contacts import Contacts as Contacts
from avito_job.models.coordinates import Coordinates as Coordinates
from avito_job.models.creation_forbidden_error import CreationForbiddenError as CreationForbiddenError
from avito_job.models.creation_forbidden_error_error import CreationForbiddenErrorError as CreationForbiddenErrorError
from avito_job.models.driver_licence import DriverLicence as DriverLicence
from avito_job.models.driving_experience import DrivingExperience as DrivingExperience
from avito_job.models.editing_forbidden_error import EditingForbiddenError as EditingForbiddenError
from avito_job.models.editing_forbidden_error_error import EditingForbiddenErrorError as EditingForbiddenErrorError
from avito_job.models.education_level import EducationLevel as EducationLevel
from avito_job.models.enriched_properties import EnrichedProperties as EnrichedProperties
from avito_job.models.enriched_properties_age import EnrichedPropertiesAge as EnrichedPropertiesAge
from avito_job.models.enriched_properties_citizenship import EnrichedPropertiesCitizenship as EnrichedPropertiesCitizenship
from avito_job.models.enriched_properties_experience import EnrichedPropertiesExperience as EnrichedPropertiesExperience
from avito_job.models.enriched_properties_full_name import EnrichedPropertiesFullName as EnrichedPropertiesFullName
from avito_job.models.enriched_properties_gender import EnrichedPropertiesGender as EnrichedPropertiesGender
from avito_job.models.enriched_properties_phone import EnrichedPropertiesPhone as EnrichedPropertiesPhone
from avito_job.models.enriched_property_matching_status import EnrichedPropertyMatchingStatus as EnrichedPropertyMatchingStatus
from avito_job.models.forbidden_error import ForbiddenError as ForbiddenError
from avito_job.models.forbidden_error_error import ForbiddenErrorError as ForbiddenErrorError
from avito_job.models.gender import Gender as Gender
from avito_job.models.get_applications_by_ids_result import GetApplicationsByIdsResult as GetApplicationsByIdsResult
from avito_job.models.get_applications_by_ids_result_applies_inner import GetApplicationsByIdsResultAppliesInner as GetApplicationsByIdsResultAppliesInner
from avito_job.models.get_applications_by_ids_result_applies_inner_applicant import GetApplicationsByIdsResultAppliesInnerApplicant as GetApplicationsByIdsResultAppliesInnerApplicant
from avito_job.models.get_applications_by_ids_result_applies_inner_applicant_data import GetApplicationsByIdsResultAppliesInnerApplicantData as GetApplicationsByIdsResultAppliesInnerApplicantData
from avito_job.models.get_applications_by_ids_result_applies_inner_applicant_data_full_name import GetApplicationsByIdsResultAppliesInnerApplicantDataFullName as GetApplicationsByIdsResultAppliesInnerApplicantDataFullName
from avito_job.models.get_applications_by_ids_result_applies_inner_contacts import GetApplicationsByIdsResultAppliesInnerContacts as GetApplicationsByIdsResultAppliesInnerContacts
from avito_job.models.get_applications_by_ids_result_applies_inner_contacts_chat import GetApplicationsByIdsResultAppliesInnerContactsChat as GetApplicationsByIdsResultAppliesInnerContactsChat
from avito_job.models.get_applications_by_ids_result_applies_inner_contacts_phones_inner import GetApplicationsByIdsResultAppliesInnerContactsPhonesInner as GetApplicationsByIdsResultAppliesInnerContactsPhonesInner
from avito_job.models.get_applications_by_ids_result_applies_inner_prevalidation import GetApplicationsByIdsResultAppliesInnerPrevalidation as GetApplicationsByIdsResultAppliesInnerPrevalidation
from avito_job.models.get_applications_by_ids_result_applies_inner_price import GetApplicationsByIdsResultAppliesInnerPrice as GetApplicationsByIdsResultAppliesInnerPrice
from avito_job.models.get_applications_ids_result import GetApplicationsIdsResult as GetApplicationsIdsResult
from avito_job.models.get_applications_ids_result_applies_inner import GetApplicationsIdsResultAppliesInner as GetApplicationsIdsResultAppliesInner
from avito_job.models.get_dict_by_id200_response_inner import GetDictByID200ResponseInner as GetDictByID200ResponseInner
from avito_job.models.get_dicts200_response_inner import GetDicts200ResponseInner as GetDicts200ResponseInner
from avito_job.models.grade import Grade as Grade
from avito_job.models.item_not_found_error import ItemNotFoundError as ItemNotFoundError
from avito_job.models.item_not_found_error_error import ItemNotFoundErrorError as ItemNotFoundErrorError
from avito_job.models.location import Location as Location
from avito_job.models.location_address import LocationAddress as LocationAddress
from avito_job.models.medical_book import MedicalBook as MedicalBook
from avito_job.models.medical_book_vacancy import MedicalBookVacancy as MedicalBookVacancy
from avito_job.models.not_found_error import NotFoundError as NotFoundError
from avito_job.models.not_found_error_error import NotFoundErrorError as NotFoundErrorError
from avito_job.models.own_transport import OwnTransport as OwnTransport
from avito_job.models.paid_period import PaidPeriod as PaidPeriod
from avito_job.models.payment_error import PaymentError as PaymentError
from avito_job.models.payment_error_error import PaymentErrorError as PaymentErrorError
from avito_job.models.phone import Phone as Phone
from avito_job.models.photo import Photo as Photo
from avito_job.models.prevalidation_answer import PrevalidationAnswer as PrevalidationAnswer
from avito_job.models.purchasing_error import PurchasingError as PurchasingError
from avito_job.models.purchasing_error_error import PurchasingErrorError as PurchasingErrorError
from avito_job.models.resume20 import Resume20 as Resume20
from avito_job.models.resume20_params import Resume20Params as Resume20Params
from avito_job.models.resume20_params_education_list_inner import Resume20ParamsEducationListInner as Resume20ParamsEducationListInner
from avito_job.models.resume20_params_experience_list_inner import Resume20ParamsExperienceListInner as Resume20ParamsExperienceListInner
from avito_job.models.resume20_params_language_list_inner import Resume20ParamsLanguageListInner as Resume20ParamsLanguageListInner
from avito_job.models.resume_contact import ResumeContact as ResumeContact
from avito_job.models.resume_contacts import ResumeContacts as ResumeContacts
from avito_job.models.resume_search_meta import ResumeSearchMeta as ResumeSearchMeta
from avito_job.models.resumes_get200_response import ResumesGet200Response as ResumesGet200Response
from avito_job.models.salary_base_range import SalaryBaseRange as SalaryBaseRange
from avito_job.models.salary_detail import SalaryDetail as SalaryDetail
from avito_job.models.salary_detail_base import SalaryDetailBase as SalaryDetailBase
from avito_job.models.search_vacancy200_response import SearchVacancy200Response as SearchVacancy200Response
from avito_job.models.search_vacancy403_response import SearchVacancy403Response as SearchVacancy403Response
from avito_job.models.search_vacancy403_response_error import SearchVacancy403ResponseError as SearchVacancy403ResponseError
from avito_job.models.service_error import ServiceError as ServiceError
from avito_job.models.service_error_error import ServiceErrorError as ServiceErrorError
from avito_job.models.service_unavailable_error import ServiceUnavailableError as ServiceUnavailableError
from avito_job.models.service_unavailable_error_error import ServiceUnavailableErrorError as ServiceUnavailableErrorError
from avito_job.models.set_applicationsis_vewed_result import SetApplicationsisVewedResult as SetApplicationsisVewedResult
from avito_job.models.set_applicationsis_vewed_result_applies_inner import SetApplicationsisVewedResultAppliesInner as SetApplicationsisVewedResultAppliesInner
from avito_job.models.simplified_resume import SimplifiedResume as SimplifiedResume
from avito_job.models.simplified_vacancy import SimplifiedVacancy as SimplifiedVacancy
from avito_job.models.simplified_vacancy_address_details import SimplifiedVacancyAddressDetails as SimplifiedVacancyAddressDetails
from avito_job.models.specialization import Specialization as Specialization
from avito_job.models.stopping_forbidden_error import StoppingForbiddenError as StoppingForbiddenError
from avito_job.models.stopping_forbidden_error_error import StoppingForbiddenErrorError as StoppingForbiddenErrorError
from avito_job.models.taxes import Taxes as Taxes
from avito_job.models.too_many_requests_error import TooManyRequestsError as TooManyRequestsError
from avito_job.models.too_many_requests_error_error import TooManyRequestsErrorError as TooManyRequestsErrorError
from avito_job.models.tools_availability import ToolsAvailability as ToolsAvailability
from avito_job.models.vacancies_get_by_ids_body import VacanciesGetByIdsBody as VacanciesGetByIdsBody
from avito_job.models.vacancy20 import Vacancy20 as Vacancy20
from avito_job.models.vacancy20_address_details import Vacancy20AddressDetails as Vacancy20AddressDetails
from avito_job.models.vacancy20_address_details_coordinates import Vacancy20AddressDetailsCoordinates as Vacancy20AddressDetailsCoordinates
from avito_job.models.vacancy20_params import Vacancy20Params as Vacancy20Params
from avito_job.models.vacancy20_params_coordinates import Vacancy20ParamsCoordinates as Vacancy20ParamsCoordinates
from avito_job.models.vacancy20_params_salary import Vacancy20ParamsSalary as Vacancy20ParamsSalary
from avito_job.models.vacancy20_params_salary_base_range import Vacancy20ParamsSalaryBaseRange as Vacancy20ParamsSalaryBaseRange
from avito_job.models.vacancy_archive import VacancyArchive as VacancyArchive
from avito_job.models.vacancy_auto_renewal import VacancyAutoRenewal as VacancyAutoRenewal
from avito_job.models.vacancy_create import VacancyCreate as VacancyCreate
from avito_job.models.vacancy_create_driving_experience import VacancyCreateDrivingExperience as VacancyCreateDrivingExperience
from avito_job.models.vacancy_create_experience import VacancyCreateExperience as VacancyCreateExperience
from avito_job.models.vacancy_create_payout_frequency import VacancyCreatePayoutFrequency as VacancyCreatePayoutFrequency
from avito_job.models.vacancy_create_result import VacancyCreateResult as VacancyCreateResult
from avito_job.models.vacancy_create_salary_range import VacancyCreateSalaryRange as VacancyCreateSalaryRange
from avito_job.models.vacancy_create_schedule import VacancyCreateSchedule as VacancyCreateSchedule
from avito_job.models.vacancy_education_level import VacancyEducationLevel as VacancyEducationLevel
from avito_job.models.vacancy_prolongate import VacancyProlongate as VacancyProlongate
from avito_job.models.vacancy_search_meta import VacancySearchMeta as VacancySearchMeta
from avito_job.models.vacancy_statuses_body import VacancyStatusesBody as VacancyStatusesBody
from avito_job.models.vacancy_statuses_result_inner import VacancyStatusesResultInner as VacancyStatusesResultInner
from avito_job.models.vacancy_statuses_result_inner_last_action import VacancyStatusesResultInnerLastAction as VacancyStatusesResultInnerLastAction
from avito_job.models.vacancy_statuses_result_inner_last_action_error import VacancyStatusesResultInnerLastActionError as VacancyStatusesResultInnerLastActionError
from avito_job.models.vacancy_statuses_result_inner_vacancy import VacancyStatusesResultInnerVacancy as VacancyStatusesResultInnerVacancy
from avito_job.models.vacancy_update import VacancyUpdate as VacancyUpdate
from avito_job.models.vacancy_update_payout_frequency import VacancyUpdatePayoutFrequency as VacancyUpdatePayoutFrequency
from avito_job.models.vacancy_update_salary_range import VacancyUpdateSalaryRange as VacancyUpdateSalaryRange
from avito_job.models.vacancy_v2_create import VacancyV2Create as VacancyV2Create
from avito_job.models.vacancy_v2_create_contacts import VacancyV2CreateContacts as VacancyV2CreateContacts
from avito_job.models.vacancy_v2_create_hierarchy import VacancyV2CreateHierarchy as VacancyV2CreateHierarchy
from avito_job.models.vacancy_v2_create_location import VacancyV2CreateLocation as VacancyV2CreateLocation
from avito_job.models.vacancy_v2_create_result import VacancyV2CreateResult as VacancyV2CreateResult
from avito_job.models.vacancy_v2_create_salary import VacancyV2CreateSalary as VacancyV2CreateSalary
from avito_job.models.validating_error import ValidatingError as ValidatingError
from avito_job.models.validating_error_error import ValidatingErrorError as ValidatingErrorError
from avito_job.models.verification_needed_error import VerificationNeededError as VerificationNeededError
from avito_job.models.verification_needed_error_error import VerificationNeededErrorError as VerificationNeededErrorError
from avito_job.models.webhook_subscribe_request_body import WebhookSubscribeRequestBody as WebhookSubscribeRequestBody
from avito_job.models.webhooks_subscription_result_list import WebhooksSubscriptionResultList as WebhooksSubscriptionResultList

