# coding: utf-8

# flake8: noqa
"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

# import models into model package
from avito_ads.models.analytics_request import AnalyticsRequest
from avito_ads.models.analytics_request_filter import AnalyticsRequestFilter
from avito_ads.models.analytics_request_sort import AnalyticsRequestSort
from avito_ads.models.analytics_response import AnalyticsResponse
from avito_ads.models.analytics_response_result import AnalyticsResponseResult
from avito_ads.models.analytics_response_result_groupings_inner import AnalyticsResponseResultGroupingsInner
from avito_ads.models.analytics_response_result_groupings_inner_metrics_inner import AnalyticsResponseResultGroupingsInnerMetricsInner
from avito_ads.models.apply_vas500_response import ApplyVas500Response
from avito_ads.models.apply_vas_request import ApplyVasRequest
from avito_ads.models.apply_vas_resp import ApplyVasResp
from avito_ads.models.auth_error import AuthError
from avito_ads.models.auth_error_error import AuthErrorError
from avito_ads.models.bad_request_error import BadRequestError
from avito_ads.models.bad_request_error_error import BadRequestErrorError
from avito_ads.models.calls_stats_day import CallsStatsDay
from avito_ads.models.calls_stats_item import CallsStatsItem
from avito_ads.models.calls_stats_request import CallsStatsRequest
from avito_ads.models.calls_stats_response import CallsStatsResponse
from avito_ads.models.calls_stats_response_result import CallsStatsResponseResult
from avito_ads.models.error_response import ErrorResponse
from avito_ads.models.error_response_error import ErrorResponseError
from avito_ads.models.field_error import FieldError
from avito_ads.models.groupings import Groupings
from avito_ads.models.info_vas import InfoVas
from avito_ads.models.item_ids_request_body import ItemIdsRequestBody
from avito_ads.models.item_info_avito import ItemInfoAvito
from avito_ads.models.item_vas_prices_resp import ItemVasPricesResp
from avito_ads.models.items_info_with_category_avito import ItemsInfoWithCategoryAvito
from avito_ads.models.items_info_with_category_avito_meta import ItemsInfoWithCategoryAvitoMeta
from avito_ads.models.items_info_with_category_avito_resources_inner import ItemsInfoWithCategoryAvitoResourcesInner
from avito_ads.models.items_info_with_category_avito_resources_inner_category import ItemsInfoWithCategoryAvitoResourcesInnerCategory
from avito_ads.models.not_found_error import NotFoundError
from avito_ads.models.not_found_error_error import NotFoundErrorError
from avito_ads.models.package_id_request_body_v2 import PackageIdRequestBodyV2
from avito_ads.models.prices_item_ids_request_body import PricesItemIdsRequestBody
from avito_ads.models.service_error import ServiceError
from avito_ads.models.service_error_error import ServiceErrorError
from avito_ads.models.service_unavailable_error import ServiceUnavailableError
from avito_ads.models.service_unavailable_error_error import ServiceUnavailableErrorError
from avito_ads.models.statistics_counters_inner import StatisticsCountersInner
from avito_ads.models.statistics_counters_inner_stats_inner import StatisticsCountersInnerStatsInner
from avito_ads.models.statistics_period_grouping import StatisticsPeriodGrouping
from avito_ads.models.statistics_response import StatisticsResponse
from avito_ads.models.statistics_response_result import StatisticsResponseResult
from avito_ads.models.statistics_shallow_request_body import StatisticsShallowRequestBody
from avito_ads.models.sticker_resp import StickerResp
from avito_ads.models.update_price_request import UpdatePriceRequest
from avito_ads.models.update_price_response import UpdatePriceResponse
from avito_ads.models.update_price_response_result import UpdatePriceResponseResult
from avito_ads.models.validating_error import ValidatingError
from avito_ads.models.validating_error_error import ValidatingErrorError
from avito_ads.models.vas_amount_avito import VasAmountAvito
from avito_ads.models.vas_apply_avito import VasApplyAvito
from avito_ads.models.vas_id_request_body import VasIdRequestBody
from avito_ads.models.vas_prices200_response import VasPrices200Response
from avito_ads.models.vas_resp import VasResp

