# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class StatisticsPeriodGrouping(str, Enum):
    """
    Период группировки
    """

    """
    allowed enum values
    """
    DAY = 'day'
    WEEK = 'week'
    MONTH = 'month'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of StatisticsPeriodGrouping from a JSON string"""
        return cls(json.loads(json_str))


