# coding: utf-8

# flake8: noqa

"""
    Мессенджер

    API Мессенджера - набор методов для получения списка чатов пользователя на Авито, получения сообщений в чате, отправки сообщения в чат и другие Через API Мессенджера можно организовать интеграцию между мессенджером Авито и сторонней системой в обе стороны  **Авито API для бизнеса предоставляется согласно [Условиям использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "MessengerApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddBlacklistRequestBody",
    "AddBlacklistRequestBodyUsersInner",
    "AddBlacklistRequestBodyUsersInnerContext",
    "AuthError",
    "AuthErrorError",
    "BadRequestError",
    "BadRequestErrorError",
    "Chat",
    "ChatContext",
    "ChatContextValue",
    "ChatContextValueImages",
    "ChatContextValueImagesMain",
    "ChatLastMessage",
    "ChatRead200Response",
    "ChatUsersInner",
    "ChatUsersInnerPublicUserProfile",
    "ChatUsersInnerPublicUserProfileAvatar",
    "ChatUsersInnerPublicUserProfileAvatarImages",
    "Chats",
    "ForbiddenError",
    "ForbiddenErrorError",
    "GetSubscriptions200Response",
    "GetSubscriptions200ResponseSubscriptionsInner",
    "MessageContent",
    "MessageContentCall",
    "MessageContentImage",
    "MessageContentItem",
    "MessageContentLink",
    "MessageContentLinkPreview",
    "MessageContentLocation",
    "MessageContentVoice",
    "MessageQuote",
    "MessagesInner",
    "NotFoundError",
    "NotFoundErrorError",
    "PayloadStruct",
    "PostSendImageMessage200Response",
    "PostSendImageMessage200ResponseContent",
    "PostSendImageMessage200ResponseContentImage",
    "PostSendMessage200Response",
    "PostSendMessage200ResponseContent",
    "PostWebhookV3201Response",
    "PurchasingError",
    "PurchasingErrorError",
    "SendImageMessageRequestBody",
    "SendMessageRequestBody",
    "SendMessageRequestBodyMessage",
    "ServiceError",
    "ServiceErrorError",
    "ServiceUnavailableError",
    "ServiceUnavailableErrorError",
    "ValidatingError",
    "ValidatingErrorError",
    "VoiceFiles",
    "WebhookMessage",
    "WebhookSubscribeRequestBody",
]

# import apis into sdk package
from avito_messenger.api.messenger_api import MessengerApi as MessengerApi

# import ApiClient
from avito_messenger.api_response import ApiResponse as ApiResponse
from avito_messenger.api_client import ApiClient as ApiClient
from avito_messenger.configuration import Configuration as Configuration
from avito_messenger.exceptions import OpenApiException as OpenApiException
from avito_messenger.exceptions import ApiTypeError as ApiTypeError
from avito_messenger.exceptions import ApiValueError as ApiValueError
from avito_messenger.exceptions import ApiKeyError as ApiKeyError
from avito_messenger.exceptions import ApiAttributeError as ApiAttributeError
from avito_messenger.exceptions import ApiException as ApiException

# import models into sdk package
from avito_messenger.models.add_blacklist_request_body import AddBlacklistRequestBody as AddBlacklistRequestBody
from avito_messenger.models.add_blacklist_request_body_users_inner import AddBlacklistRequestBodyUsersInner as AddBlacklistRequestBodyUsersInner
from avito_messenger.models.add_blacklist_request_body_users_inner_context import AddBlacklistRequestBodyUsersInnerContext as AddBlacklistRequestBodyUsersInnerContext
from avito_messenger.models.auth_error import AuthError as AuthError
from avito_messenger.models.auth_error_error import AuthErrorError as AuthErrorError
from avito_messenger.models.bad_request_error import BadRequestError as BadRequestError
from avito_messenger.models.bad_request_error_error import BadRequestErrorError as BadRequestErrorError
from avito_messenger.models.chat import Chat as Chat
from avito_messenger.models.chat_context import ChatContext as ChatContext
from avito_messenger.models.chat_context_value import ChatContextValue as ChatContextValue
from avito_messenger.models.chat_context_value_images import ChatContextValueImages as ChatContextValueImages
from avito_messenger.models.chat_context_value_images_main import ChatContextValueImagesMain as ChatContextValueImagesMain
from avito_messenger.models.chat_last_message import ChatLastMessage as ChatLastMessage
from avito_messenger.models.chat_read200_response import ChatRead200Response as ChatRead200Response
from avito_messenger.models.chat_users_inner import ChatUsersInner as ChatUsersInner
from avito_messenger.models.chat_users_inner_public_user_profile import ChatUsersInnerPublicUserProfile as ChatUsersInnerPublicUserProfile
from avito_messenger.models.chat_users_inner_public_user_profile_avatar import ChatUsersInnerPublicUserProfileAvatar as ChatUsersInnerPublicUserProfileAvatar
from avito_messenger.models.chat_users_inner_public_user_profile_avatar_images import ChatUsersInnerPublicUserProfileAvatarImages as ChatUsersInnerPublicUserProfileAvatarImages
from avito_messenger.models.chats import Chats as Chats
from avito_messenger.models.forbidden_error import ForbiddenError as ForbiddenError
from avito_messenger.models.forbidden_error_error import ForbiddenErrorError as ForbiddenErrorError
from avito_messenger.models.get_subscriptions200_response import GetSubscriptions200Response as GetSubscriptions200Response
from avito_messenger.models.get_subscriptions200_response_subscriptions_inner import GetSubscriptions200ResponseSubscriptionsInner as GetSubscriptions200ResponseSubscriptionsInner
from avito_messenger.models.message_content import MessageContent as MessageContent
from avito_messenger.models.message_content_call import MessageContentCall as MessageContentCall
from avito_messenger.models.message_content_image import MessageContentImage as MessageContentImage
from avito_messenger.models.message_content_item import MessageContentItem as MessageContentItem
from avito_messenger.models.message_content_link import MessageContentLink as MessageContentLink
from avito_messenger.models.message_content_link_preview import MessageContentLinkPreview as MessageContentLinkPreview
from avito_messenger.models.message_content_location import MessageContentLocation as MessageContentLocation
from avito_messenger.models.message_content_voice import MessageContentVoice as MessageContentVoice
from avito_messenger.models.message_quote import MessageQuote as MessageQuote
from avito_messenger.models.messages_inner import MessagesInner as MessagesInner
from avito_messenger.models.not_found_error import NotFoundError as NotFoundError
from avito_messenger.models.not_found_error_error import NotFoundErrorError as NotFoundErrorError
from avito_messenger.models.payload_struct import PayloadStruct as PayloadStruct
from avito_messenger.models.post_send_image_message200_response import PostSendImageMessage200Response as PostSendImageMessage200Response
from avito_messenger.models.post_send_image_message200_response_content import PostSendImageMessage200ResponseContent as PostSendImageMessage200ResponseContent
from avito_messenger.models.post_send_image_message200_response_content_image import PostSendImageMessage200ResponseContentImage as PostSendImageMessage200ResponseContentImage
from avito_messenger.models.post_send_message200_response import PostSendMessage200Response as PostSendMessage200Response
from avito_messenger.models.post_send_message200_response_content import PostSendMessage200ResponseContent as PostSendMessage200ResponseContent
from avito_messenger.models.post_webhook_v3201_response import PostWebhookV3201Response as PostWebhookV3201Response
from avito_messenger.models.purchasing_error import PurchasingError as PurchasingError
from avito_messenger.models.purchasing_error_error import PurchasingErrorError as PurchasingErrorError
from avito_messenger.models.send_image_message_request_body import SendImageMessageRequestBody as SendImageMessageRequestBody
from avito_messenger.models.send_message_request_body import SendMessageRequestBody as SendMessageRequestBody
from avito_messenger.models.send_message_request_body_message import SendMessageRequestBodyMessage as SendMessageRequestBodyMessage
from avito_messenger.models.service_error import ServiceError as ServiceError
from avito_messenger.models.service_error_error import ServiceErrorError as ServiceErrorError
from avito_messenger.models.service_unavailable_error import ServiceUnavailableError as ServiceUnavailableError
from avito_messenger.models.service_unavailable_error_error import ServiceUnavailableErrorError as ServiceUnavailableErrorError
from avito_messenger.models.validating_error import ValidatingError as ValidatingError
from avito_messenger.models.validating_error_error import ValidatingErrorError as ValidatingErrorError
from avito_messenger.models.voice_files import VoiceFiles as VoiceFiles
from avito_messenger.models.webhook_message import WebhookMessage as WebhookMessage
from avito_messenger.models.webhook_subscribe_request_body import WebhookSubscribeRequestBody as WebhookSubscribeRequestBody

