# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.update_price_response import UpdatePriceResponse

class TestUpdatePriceResponse(unittest.TestCase):
    """UpdatePriceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdatePriceResponse:
        """Test UpdatePriceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdatePriceResponse`
        """
        model = UpdatePriceResponse()
        if include_optional:
            return UpdatePriceResponse(
                result = avito_ads.models.update_price_response_result.UpdatePriceResponse_result(
                    success = True, )
            )
        else:
            return UpdatePriceResponse(
                result = avito_ads.models.update_price_response_result.UpdatePriceResponse_result(
                    success = True, ),
        )
        """

    def testUpdatePriceResponse(self):
        """Test UpdatePriceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
