# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.groupings import Groupings

class TestGroupings(unittest.TestCase):
    """Groupings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupings(self):
        """Test Groupings"""
        # inst = Groupings()

if __name__ == '__main__':
    unittest.main()
