# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.api.item_api import ItemApi


class TestItemApi(unittest.TestCase):
    """ItemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ItemApi()

    def tearDown(self) -> None:
        pass

    def test_apply_vas(self) -> None:
        """Test case for apply_vas

        Применение услуг продвижения
        """
        pass

    def test_get_item_info(self) -> None:
        """Test case for get_item_info

        Получение информации по объявлению
        """
        pass

    def test_get_items_info(self) -> None:
        """Test case for get_items_info

        Получение информации по объявлениям
        """
        pass

    def test_item_analytics(self) -> None:
        """Test case for item_analytics

        Получение статистических показателей по профилю
        """
        pass

    def test_item_stats_shallow(self) -> None:
        """Test case for item_stats_shallow

        Получение статистики по списку объявлений
        """
        pass

    def test_post_calls_stats(self) -> None:
        """Test case for post_calls_stats

        Получение статистики по звонкам
        """
        pass

    def test_put_item_vas(self) -> None:
        """Test case for put_item_vas

        Применение дополнительных услуг
        """
        pass

    def test_put_item_vas_package_v2(self) -> None:
        """Test case for put_item_vas_package_v2

        Применение пакета дополнительных услуг
        """
        pass

    def test_vas_prices(self) -> None:
        """Test case for vas_prices

        Получение информации о стоимости услуг продвижения и доступных значках
        """
        pass


if __name__ == '__main__':
    unittest.main()
