# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.statistics_counters_inner_stats_inner import StatisticsCountersInnerStatsInner

class TestStatisticsCountersInnerStatsInner(unittest.TestCase):
    """StatisticsCountersInnerStatsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatisticsCountersInnerStatsInner:
        """Test StatisticsCountersInnerStatsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatisticsCountersInnerStatsInner`
        """
        model = StatisticsCountersInnerStatsInner()
        if include_optional:
            return StatisticsCountersInnerStatsInner(
                contacts = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                favorites = 56,
                uniq_contacts = 56,
                uniq_favorites = 56,
                uniq_views = 56,
                views = 56
            )
        else:
            return StatisticsCountersInnerStatsInner(
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testStatisticsCountersInnerStatsInner(self):
        """Test StatisticsCountersInnerStatsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
