# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.calls_stats_response import CallsStatsResponse

class TestCallsStatsResponse(unittest.TestCase):
    """CallsStatsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CallsStatsResponse:
        """Test CallsStatsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CallsStatsResponse`
        """
        model = CallsStatsResponse()
        if include_optional:
            return CallsStatsResponse(
                result = avito_ads.models.calls_stats_response_result.CallsStatsResponse_result(
                    items = [
                        avito_ads.models.calls_stats_item.CallsStatsItem(
                            days = [
                                avito_ads.models.calls_stats_day.CallsStatsDay(
                                    answered = 56, 
                                    calls = 56, 
                                    date = '', 
                                    new = 56, 
                                    new_answered = 56, )
                                ], 
                            employee_id = 56, 
                            item_id = 56, )
                        ], )
            )
        else:
            return CallsStatsResponse(
        )
        """

    def testCallsStatsResponse(self):
        """Test CallsStatsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
