# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.analytics_request_filter import AnalyticsRequestFilter

class TestAnalyticsRequestFilter(unittest.TestCase):
    """AnalyticsRequestFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsRequestFilter:
        """Test AnalyticsRequestFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsRequestFilter`
        """
        model = AnalyticsRequestFilter()
        if include_optional:
            return AnalyticsRequestFilter(
                category_ids = [11,12],
                employee_ids = [41042142,41042143]
            )
        else:
            return AnalyticsRequestFilter(
        )
        """

    def testAnalyticsRequestFilter(self):
        """Test AnalyticsRequestFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
