# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.vas_prices200_response import VasPrices200Response

class TestVasPrices200Response(unittest.TestCase):
    """VasPrices200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VasPrices200Response:
        """Test VasPrices200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VasPrices200Response`
        """
        model = VasPrices200Response()
        if include_optional:
            return VasPrices200Response(
                error = avito_ads.models.auth_error_error.authError_error(
                    code = 401, 
                    message = 'Unauthorized', )
            )
        else:
            return VasPrices200Response(
        )
        """

    def testVasPrices200Response(self):
        """Test VasPrices200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
