# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.items_info_with_category_avito_resources_inner_category import ItemsInfoWithCategoryAvitoResourcesInnerCategory

class TestItemsInfoWithCategoryAvitoResourcesInnerCategory(unittest.TestCase):
    """ItemsInfoWithCategoryAvitoResourcesInnerCategory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsInfoWithCategoryAvitoResourcesInnerCategory:
        """Test ItemsInfoWithCategoryAvitoResourcesInnerCategory
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsInfoWithCategoryAvitoResourcesInnerCategory`
        """
        model = ItemsInfoWithCategoryAvitoResourcesInnerCategory()
        if include_optional:
            return ItemsInfoWithCategoryAvitoResourcesInnerCategory(
                id = 111,
                name = 'Вакансии'
            )
        else:
            return ItemsInfoWithCategoryAvitoResourcesInnerCategory(
        )
        """

    def testItemsInfoWithCategoryAvitoResourcesInnerCategory(self):
        """Test ItemsInfoWithCategoryAvitoResourcesInnerCategory"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
