# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.item_vas_prices_resp import ItemVasPricesResp

class TestItemVasPricesResp(unittest.TestCase):
    """ItemVasPricesResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemVasPricesResp:
        """Test ItemVasPricesResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemVasPricesResp`
        """
        model = ItemVasPricesResp()
        if include_optional:
            return ItemVasPricesResp(
                item_id = 56,
                stickers = [
                    avito_ads.models.sticker_resp.StickerResp(
                        description = '', 
                        id = 56, 
                        title = '', )
                    ],
                vas = [
                    avito_ads.models.vas_resp.VasResp(
                        price = 200, 
                        price_old = 300, 
                        slug = 'x2_1', )
                    ]
            )
        else:
            return ItemVasPricesResp(
                vas = [
                    avito_ads.models.vas_resp.VasResp(
                        price = 200, 
                        price_old = 300, 
                        slug = 'x2_1', )
                    ],
        )
        """

    def testItemVasPricesResp(self):
        """Test ItemVasPricesResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
