# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.apply_vas_resp import ApplyVasResp

class TestApplyVasResp(unittest.TestCase):
    """ApplyVasResp unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplyVasResp:
        """Test ApplyVasResp
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplyVasResp`
        """
        model = ApplyVasResp()
        if include_optional:
            return ApplyVasResp(
                operation_id = 56
            )
        else:
            return ApplyVasResp(
                operation_id = 56,
        )
        """

    def testApplyVasResp(self):
        """Test ApplyVasResp"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
