# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.analytics_response import AnalyticsResponse

class TestAnalyticsResponse(unittest.TestCase):
    """AnalyticsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AnalyticsResponse:
        """Test AnalyticsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AnalyticsResponse`
        """
        model = AnalyticsResponse()
        if include_optional:
            return AnalyticsResponse(
                result = avito_ads.models.analytics_response_result.AnalyticsResponse_result(
                    data_total_count = 1, 
                    groupings = [{"id":1742860800,"metrics":[{"slug":"views","value":100},{"slug":"contacts","value":100},{"slug":"presenceSpending","value":1000}],"type":"dates"}], 
                    timestamp = '2021-11-25 15:19:21', )
            )
        else:
            return AnalyticsResponse(
        )
        """

    def testAnalyticsResponse(self):
        """Test AnalyticsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
