# coding: utf-8

"""
    Объявления

    API для получение статистики по объявлениям, применения дополнительных услуг, а также просмотр статусов объявлений  **Авито API для бизнеса предоставляется согласно [Условиям   использования](https://www.avito.ru/legal/pro_tools/public-api).** 

    The version of the OpenAPI document: 1
    Contact: supportautoload@avito.ru
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from avito_ads.models.items_info_with_category_avito import ItemsInfoWithCategoryAvito

class TestItemsInfoWithCategoryAvito(unittest.TestCase):
    """ItemsInfoWithCategoryAvito unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ItemsInfoWithCategoryAvito:
        """Test ItemsInfoWithCategoryAvito
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ItemsInfoWithCategoryAvito`
        """
        model = ItemsInfoWithCategoryAvito()
        if include_optional:
            return ItemsInfoWithCategoryAvito(
                meta = avito_ads.models.items_info_with_category_avito_meta.ItemsInfoWithCategoryAvito_meta(
                    page = 1, 
                    per_page = 25, ),
                resources = [
                    avito_ads.models.items_info_with_category_avito_resources_inner.ItemsInfoWithCategoryAvito_resources_inner(
                        address = 'Москва, Лесная улица 7', 
                        category = avito_ads.models.items_info_with_category_avito_resources_inner_category.ItemsInfoWithCategoryAvito_resources_inner_category(
                            id = 111, 
                            name = 'Вакансии', ), 
                        id = 24122231, 
                        price = 35000, 
                        status = 'active', 
                        title = 'Продавец-кассир', 
                        url = 'https://www.avito.ru/rostov-na-donu/vakansii/prodavets_magazina_2142', )
                    ]
            )
        else:
            return ItemsInfoWithCategoryAvito(
        )
        """

    def testItemsInfoWithCategoryAvito(self):
        """Test ItemsInfoWithCategoryAvito"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
